LOCAL_TOOLCHAIN := arm-eabi-
UBOOT_OUT := $(TARGET_OUT_INTERMEDIATES)/u-boot
#UBOOT_OUT := u-boot
UBOOT_BUILT_SPL := $(UBOOT_OUT)/nand_spl/u-boot-spl-16k.bin
UBOOT_BUILT_BIN := $(UBOOT_OUT)/u-boot.bin
UBOOT_BUILT_FDL := $(UBOOT_OUT)/nand_fdl/fdl2.bin
UBOOT_CONFIG := $(UBOOT_OUT)/include/config.h
AUTOBOOT_BIN := u-boot_autopoweron.bin
ifeq ($(RAM512_BINGEN_SUPPORT),true)
UBOOT_BIN_RAM512 := u-boot-ram512.bin
UBOOT_FDL_RAM512 := fdl2-ram512.bin
endif
export PRODUCT_OUT UBOOT_OUT

.PHONY: $(UBOOT_OUT)
$(UBOOT_OUT):
	@echo "Start U-Boot build"

$(UBOOT_CONFIG): u-boot/include/configs/$(addsuffix .h,$(UBOOT_DEFCONFIG)) $(UBOOT_OUT)
	@mkdir -p $(UBOOT_OUT)
	$(MAKE) -C u-boot CROSS_COMPILE=$(LOCAL_TOOLCHAIN) O=../$(UBOOT_OUT) distclean
	$(MAKE) -C u-boot CROSS_COMPILE=$(LOCAL_TOOLCHAIN) O=../$(UBOOT_OUT) $(UBOOT_DEFCONFIG)_config

$(INSTALLED_UBOOT_TARGET) : $(UBOOT_CONFIG)
	$(MAKE) -C u-boot CROSS_COMPILE=$(LOCAL_TOOLCHAIN) AP_VERSION="$(ANDROID_BUILD_DESC)" O=../$(UBOOT_OUT)
	$(MAKE) -C u-boot CROSS_COMPILE=$(LOCAL_TOOLCHAIN) AP_VERSION="$(ANDROID_BUILD_DESC)" O=../$(UBOOT_OUT) fdl2
	@cp $(UBOOT_BUILT_SPL) $(PRODUCT_OUT)
	@cp $(UBOOT_BUILT_BIN) $(PRODUCT_OUT)
	@cp $(UBOOT_BUILT_FDL) $(PRODUCT_OUT)
	$(MAKE) -C u-boot CROSS_COMPILE=$(LOCAL_TOOLCHAIN) O=../$(UBOOT_OUT) clean
	$(MAKE) -C u-boot CROSS_COMPILE=$(LOCAL_TOOLCHAIN) AP_VERSION="$(ANDROID_BUILD_DESC)" AUTOBOOT_FLAG=true O=../$(UBOOT_OUT)
	@cp $(UBOOT_BUILT_BIN) $(PRODUCT_OUT)/${AUTOBOOT_BIN}
ifeq ($(RAM512_BINGEN_SUPPORT),true)
	$(MAKE) -C u-boot CROSS_COMPILE=$(LOCAL_TOOLCHAIN) O=../$(UBOOT_OUT) clean
	$(MAKE) -C u-boot CROSS_COMPILE=$(LOCAL_TOOLCHAIN) AP_VERSION="$(ANDROID_BUILD_DESC)" RAM_4G_SUPPORT=true ROM_8G_SUPPORT=true O=../$(UBOOT_OUT)
	$(MAKE) -C u-boot CROSS_COMPILE=$(LOCAL_TOOLCHAIN) AP_VERSION="$(ANDROID_BUILD_DESC)" RAM_4G_SUPPORT=true ROM_8G_SUPPORT=true O=../$(UBOOT_OUT) fdl2
	@cp $(UBOOT_BUILT_BIN) $(PRODUCT_OUT)/${UBOOT_BIN_RAM512}
	@cp $(UBOOT_BUILT_FDL) $(PRODUCT_OUT)/${UBOOT_FDL_RAM512}
endif
	@echo "Install U-Boot target done"


