#include <config.h>
#include "../../../disk/part_uefi.h"

#ifdef CONFIG_SC8830
PARTITION_CFG const g_sprd_emmc_partition_cfg[MAX_PARTITION_INFO] = {
	{PARTITION_TDMODEM, 	10 * 1024,	PARTITION_RAW,0,L"tdmodem"},
	{PARTITION_TDDSP, 	5 * 1024, 	PARTITION_RAW,0,L"tddsp"},
	{PARTITION_TDFIX_NV1, 	3840, 		PARTITION_RAW,0,L"tdfixnv1"},
	{PARTITION_TDFIX_NV2, 	3840, 		PARTITION_RAW,0,L"tdfixnv2"},
	{PARTITION_TDRUNTIME_NV1, 3840, 	PARTITION_RAW,0,L"tdruntimenv1"},
	{PARTITION_TDRUNTIME_NV2, 3840, 	PARTITION_RAW,0,L"tdruntimenv2"},
	{PARTITION_WMODEM, 	10 * 1024, 	PARTITION_RAW,0,L"wmodem"},
	{PARTITION_WDSP, 	5 * 1024, 	PARTITION_RAW,0,L"wdsp"},
	{PARTITION_WFIX_NV1, 	3840, 		PARTITION_RAW,0,L"wfixnv1"},
	{PARTITION_WFIX_NV2, 	3840, 		PARTITION_RAW,0,L"wfixnv2"},
	{PARTITION_WRUNTIME_NV1,3840, 		PARTITION_RAW,0,L"wruntimenv1"},
	{PARTITION_WRUNTIME_NV2,3840, 		PARTITION_RAW,0,L"wruntimenv2"},
	{PARTITION_PROD_INFO1, 	3840, 		PARTITION_RAW,0,L"prodinfo1"},
	{PARTITION_PROD_INFO2, 	3840, 		PARTITION_RAW,0,L"prodinfo2"},
	{PARTITION_PROD_INFO3, 	5 * 1024, 	PARTITION_RAW,0,L"prodinfo3"},
	{PARTITION_LOGO, 	1 * 1024, 	PARTITION_RAW,0,L"logo"},
	{PARTITION_FASTBOOT_LOGO, 1 * 1024, 	PARTITION_RAW,0,L"fbootlogo"},
	{PARTITION_KERNEL, 	10 * 1024, 	PARTITION_RAW,0,L"kenel"},
	{PARTITION_SYSTEM, 	300 * 1024, 	PARTITION_RAW,0,L"system"},
	{PARTITION_CACHE, 	150 * 1024, 	PARTITION_RAW,0,L"cache"},
	{PARTITION_RECOVERY, 	10 * 1024, 	PARTITION_RAW,0,L"recovery"},
	{PARTITION_MISC, 	256, 		PARTITION_RAW,0,L"misc"},
	{PARTITION_SD, 		1000 * 1024, 	PARTITION_RAW,0,L"sd"},
	{PARTITION_PROD_INFO4, 	256, 		PARTITION_RAW,0,L"prodinfo4"},
	{PARTITION_USER_DAT, 	MAX_SIZE_FLAG, 	PARTITION_RAW,0,L"userdata"},
        {0, 0, 0,0,L""}
};
#elif defined CONFIG_SP8830EC
PARTITION_CFG const g_sprd_emmc_partition_cfg[MAX_PARTITION_INFO] = {
	{PARTITION_TDMODEM, 	10 * 1024,	PARTITION_RAW,0,L"tdmodem"},
	{PARTITION_TDDSP, 	5 * 1024, 	PARTITION_RAW,0,L"tddsp"},
	{PARTITION_TDFIX_NV1, 	3840, 		PARTITION_RAW,0,L"tdfixnv1"},
	{PARTITION_TDFIX_NV2, 	3840, 		PARTITION_RAW,0,L"tdfixnv2"},
	{PARTITION_TDRUNTIME_NV1, 3840, 	PARTITION_RAW,0,L"tdruntimenv1"},
	{PARTITION_TDRUNTIME_NV2, 3840, 	PARTITION_RAW,0,L"tdruntimenv2"},
	{PARTITION_PROD_INFO1, 	3840, 		PARTITION_RAW,0,L"prodinfo1"},
	{PARTITION_PROD_INFO2, 	3840, 		PARTITION_RAW,0,L"prodinfo2"},
	{PARTITION_PROD_INFO3, 	5 * 1024, 	PARTITION_RAW,0,L"prodinfo3"},
	{PARTITION_LOGO, 	1 * 1024, 	PARTITION_RAW,0,L"logo"},
	{PARTITION_FASTBOOT_LOGO, 1 * 1024, 	PARTITION_RAW,0,L"fbootlogo"},
	{PARTITION_KERNEL, 	10 * 1024, 	PARTITION_RAW,0,L"kenel"},
	{PARTITION_SYSTEM, 	300 * 1024, 	PARTITION_RAW,0,L"system"},
	{PARTITION_CACHE, 	150 * 1024, 	PARTITION_RAW,0,L"cache"},
	{PARTITION_RECOVERY, 	10 * 1024, 	PARTITION_RAW,0,L"recovery"},
	{PARTITION_MISC, 	256, 		PARTITION_RAW,0,L"misc"},
	{PARTITION_SD, 		1000 * 1024, 	PARTITION_RAW,0,L"sd"},
	{PARTITION_PROD_INFO4, 	256, 		PARTITION_RAW,0,L"prodinfo4"},
	{PARTITION_USER_DAT, 	MAX_SIZE_FLAG, 	PARTITION_RAW,0,L"userdata"},
        {0, 0, 0,0,""}
};	
#elif defined CONFIG_SP7735EC
PARTITION_CFG const g_sprd_emmc_partition_cfg[MAX_PARTITION_INFO] = {
	{PARTITION_WMODEM, 	10 * 1024, 	PARTITION_RAW,0,L"wmodem"},
	{PARTITION_WDSP, 	5 * 1024, 	PARTITION_RAW,0,L"wdsp"},
	{PARTITION_WFIX_NV1, 	3840, 		PARTITION_RAW,0,L"wfixnv1"},
	{PARTITION_WFIX_NV2, 	3840, 		PARTITION_RAW,0,L"wfixnv2"},
	{PARTITION_WRUNTIME_NV1,3840, 		PARTITION_RAW,0,L"wruntimenv1"},
	{PARTITION_WRUNTIME_NV2,3840, 		PARTITION_RAW,0,L"wruntimenv2"},
	{PARTITION_PROD_INFO1, 	3840, 		PARTITION_RAW,0,L"prodinfo1"},
	{PARTITION_PROD_INFO2, 	3840, 		PARTITION_RAW,0,L"prodinfo2"},
	{PARTITION_PROD_INFO3, 	5 * 1024, 	PARTITION_RAW,0,L"prodinfo3"},
	{PARTITION_LOGO, 	1 * 1024, 	PARTITION_RAW,0,L"logo"},
	{PARTITION_FASTBOOT_LOGO,1 * 1024, 	PARTITION_RAW,0,L"fbootlogo"},
	{PARTITION_KERNEL, 	10 * 1024, 	PARTITION_RAW,0,L"kernel"},
	{PARTITION_SYSTEM,	300 * 1024, 	PARTITION_RAW,0,L"system"},
	{PARTITION_CACHE, 	150 * 1024, 	PARTITION_RAW,0,L"cache"},
	{PARTITION_RECOVERY, 	10 * 1024, 	PARTITION_RAW,0,L"recovery"},
	{PARTITION_MISC, 	256, 		PARTITION_RAW,0,L"misc"},
	{PARTITION_SD, 		1000 * 1024, 	PARTITION_RAW,0,L"sd"},
	{PARTITION_PROD_INFO4, 	256, 		PARTITION_RAW,0,L"prodinfo4"},
	{PARTITION_USER_DAT, 	MAX_SIZE_FLAG, 	PARTITION_RAW,0,L"userdata"},
        {0, 0, 0,0,L""}
};	
#else
PARTITION_CFG const g_sprd_emmc_partition_cfg[MAX_PARTITION_INFO] = {
	{PARTITION_VM, 		512, 		PARTITION_RAW,0,L"vm"},/* 512KB , save modem fdl in samsung stingray*/
	{PARTITION_MODEM, 	10 * 1024, 	PARTITION_RAW,0,L"modem"},/* 10 * 1024KB not used in samsung stingray*/
	{PARTITION_DSP, 	5 * 1024, 	PARTITION_RAW,0,L"dsp"},/*save dsp image in samsung stingray*/
	{PARTITION_FIX_NV1, 	3840, 		PARTITION_RAW,0,L"fixnv1"},
	{PARTITION_FIX_NV2, 	3840, 		PARTITION_RAW,0,L"fixnv2"},
	{PARTITION_RUNTIME_NV1, 3840, 		PARTITION_RAW,0,L"runtimenv1"},
	{PARTITION_RUNTIME_NV2, 3840, 		PARTITION_RAW,0,L"runtimenv2"},
	{PARTITION_PROD_INFO1, 	3840, 		PARTITION_RAW,0,L"prodinfo1"},
	{PARTITION_PROD_INFO2, 	3840, 		PARTITION_RAW,0,L"prodinfo2"},
	{PARTITION_PROD_INFO3, 	5 * 1024, 	PARTITION_RAW,0,L"prodinfo3"}, /* must be large or equal than 5MB */
	{PARTITION_KERNEL, 	10 * 1024, 	PARTITION_RAW,0,L"kernel"},
	{PARTITION_SYSTEM, 	300 * 1024, 	PARTITION_RAW,0,L"system"},
	{PARTITION_USER_DAT, 	MAX_SIZE_FLAG, 	PARTITION_RAW,0,L"userdata"},
	{PARTITION_CACHE, 	150 * 1024, 	PARTITION_RAW,0,L"cache"},
	{PARTITION_LOGO, 	1 * 1024, 	PARTITION_RAW,0,L"logo"},
	{PARTITION_RECOVERY, 	10 * 1024, 	PARTITION_RAW,0,L"recovery"},
	{PARTITION_FASTBOOT_LOGO,1 * 1024, 	PARTITION_RAW,0,L"fbootlogo"},
	{PARTITION_MISC,	 256, 		PARTITION_RAW,0,L"misc"},
#if defined(CONFIG_SP7702) || defined(CONFIG_SP8810W) || defined (CONFIG_SC7710G2)
	{PARTITION_FIRMWARE, 	10*1024, 	PARTITION_RAW,0,L"firmware"},   /*save modem image in samsung stingray0*/
#else
	{PARTITION_SD, 		1000 * 1024, 	PARTITION_RAW,0,L"sd"},
#endif
#ifdef CONFIG_SIMLOCK
	{PARTITION_SIMLOCK, 	512, 		PARTITION_RAW,0,L"simlock"},
#endif
        {0, 0, 0,0,L""}
};
#endif
